SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tblMqttTopic](
	[_id] [int] IDENTITY(1,1) NOT NULL,
	[url] [dbo].[en_url] NOT NULL,
	[topic] [nvarchar](64) NOT NULL,
	[date] [datetime] NULL,
 CONSTRAINT [PK_tblMqttTopic] PRIMARY KEY CLUSTERED 
(
	[_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


