EXEC prcUiWordUpdate 'url', N'URL', N'URL', N'URL'
EXEC prcUiWordUpdate 'unit-id', N'Unit ID', N'Įrenginio ID', N'ИД устройства'
EXEC prcUiWordUpdate 'measure-unit', N'Measure Unit', N'Matavimo vienetas', N'Единица измерения'
EXEC prcUiWordUpdate 'register-address', N'Register address', N'Registro adresas', N'Адрес регистра'
EXEC prcUiWordUpdate 'register-type', N'Register type', N'Registro tipas', N'Тип регистра'
EXEC prcUiWordUpdate 'function-code', N'Function code', N'Funkcijos kodas', N'Код функции'
EXEC prcUiWordUpdate 'multiplier', N'Multiplier', N'Daugiklis', N'Множитель'
EXEC prcUiWordUpdate 'offset', N'Offset', N'Kompensacija', N'Компенсация'
EXEC prcUiWordUpdate 'device-id', N'Device ID', N'Įrenginio ID', N'ИД устройства'
EXEC prcUiWordUpdate 'add-datapoint', N'Add datapoint', N'Pridėti duomenų tašką', N'Добавить точку данных'
EXEC prcUiWordUpdate 'datapoint', N'Datapoint', N'Duomenų taškas', N'Точка данных'
EXEC prcUiWordUpdate 'datapoints', N'Datapoints', N'Duomenų taškai', N'Точки данных'
EXEC prcUiWordUpdate 'new-datapoint', N'New datapoint', N'Naujas duomenų taškas', N'Новая точка данных'
EXEC prcUiWordUpdate 'delete', N'Delete', N'Ištrinti', N'Удалить'
EXEC prcUiWordUpdate 'new-device', N'New device', N'Naujas įrenginys', N'Новое устройство'
