USE [ExperimentDB]
GO
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'aggregation', N'en', N'Aggregation', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'aggregation', N'lt', N'Agregavimas', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'aggregation', N'ru', N'Агрегация', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'alarms', N'en', N'Alarms', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'alarms', N'lt', N'Ekosistema', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'alarms', N'ru', N'Экосистема', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'algorithms', N'en', N'Algorithms', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'algorithms', N'lt', N'Algoritmai', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'algorithms', N'ru', N'Алгоритмы', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'app-name', N'en', N'Experiment', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'app-name', N'lt', N'Eksperimentas', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'app-name', N'ru', N'Эксперимент', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'area', N'en', N'Area', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'area', N'lt', N'Plotas', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'area', N'ru', N'Площадь', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'attention', N'en', N'Attention', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'attention', N'lt', N'Dėmesio', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'attention', N'ru', N'Внимание', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'average-value', N'en', N'Average value', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'average-value', N'lt', N'Vidurkis', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'average-value', N'ru', N'Среднее значение', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'back', N'en', N'Back', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'back', N'lt', N'Atgal', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'back', N'ru', N'Назад', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'bar', N'en', N'Bars', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'bar', N'lt', N'Juostos', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'bar', N'ru', N'Линии', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'bluetooth', N'en', N'Bluetooth', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'bluetooth', N'lt', N'Bluetooth', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'bluetooth', N'ru', N'Bluetooth', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'cancel', N'en', N'Cancel', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'cancel', N'lt', N'Atšaukti', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'cancel', N'ru', N'Отменить', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'cdate', N'en', N'Creation date', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'cdate', N'lt', N'Sukūrimo data', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'cdate', N'ru', N'Дата создания', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'chart', N'en', N'Chart', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'chart', N'lt', N'Grafikas', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'chart', N'ru', N'График', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'contact-us', N'en', N'Contact Us', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'contact-us', N'lt', N'Susisiekite su mumis', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'contact-us', N'ru', N'Связаться с нами', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'day', N'en', N'Day', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'day', N'lt', N'Diena', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'day', N'ru', N'День', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'data', N'en', N'Data', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'data', N'lt', N'Duomenys', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'data', N'ru', N'Данные', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'date', N'en', N'Date', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'date', N'lt', N'Data', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'date', N'ru', N'Дата', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'date-range', N'en', N'Date range', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'date-range', N'lt', N'Datos diapazonas', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'date-range', N'ru', N'Диапазон дат', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'delete', N'en', N'Delete', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'delete', N'lt', N'Pašalinti', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'delete', N'ru', N'Удалить', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'description', N'en', N'Description', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'description', N'lt', N'Aprašymas', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'description', N'ru', N'Описание', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'deterioration', N'en', N'Deterioration', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'deterioration', N'lt', N'Nusidėvėjimas', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'deterioration', N'ru', N'Амортизация', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'deviceId', N'en', N'Device''s Id', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'deviceId', N'lt', N'Įrenginio Id', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'deviceId', N'ru', N'Ид устройства', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'devices', N'en', N'Devices', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'devices', N'lt', N'Įrenginiai', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'devices', N'ru', N'Устройства', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'done', N'en', N'Done', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'done', N'lt', N'Atlikta', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'done', N'ru', N'Готово', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'donut', N'en', N'Donut', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'donut', N'lt', N'Riestainis', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'donut', N'ru', N'Бублик', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'download', N'en', N'Download', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'download', N'lt', N'Atsisiųsti', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'download', N'ru', N'Скачать', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'ecosystem', N'en', N'Ecosystem', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'ecosystem', N'lt', N'Ekosistema', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'ecosystem', N'ru', N'Экосистема', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'email', N'en', N'E-mail', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'email', N'lt', N'Elektroninis paštas', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'email', N'ru', N'Электронная почта', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'engineering', N'en', N'Engineering', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'engineering', N'lt', N'Inžinerija', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'engineering', N'ru', N'Инженерия', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'err-list-load', N'en', N'The list failed to load', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'err-list-load', N'lt', N'Nepavyko užkrauti sąrašo', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'err-list-load', N'ru', N'Не удалось загрузить список', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'err-login-failed', N'en', N'Login failed', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'err-login-failed', N'lt', N'Prisijungimas nepavyko', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'err-login-failed', N'ru', N'Авторизация не удалась', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'err-op', N'en', N'Operation failed.', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'err-op', N'lt', N'Operacija nesėkminga.', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'err-op', N'ru', N'Операция не удалась.', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'error-empty-req-fields', N'en', N'Please fill required fields!', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'error-empty-req-fields', N'lt', N'Prašome užpildyti privalomus laukus!', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'error-empty-req-fields', N'ru', N'Пожалуйста, заполните обязательные поля!', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'error-numeric', N'en', N'should be numeric!', 0)
GO
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'error-numeric', N'lt', N'turi būti skaičius!', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'error-numeric', N'ru', N'это числовая величина!', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'err-registration', N'en', N'Registration failed.', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'err-registration', N'lt', N'Registracija nepavyko.', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'err-registration', N'ru', N'Регистрация не удалась.', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'err-wrong-usrpas', N'en', N'Wrong username or password.', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'err-wrong-usrpas', N'lt', N'Neteisingas vartotojo vardas arba slaptažodis.', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'err-wrong-usrpas', N'ru', N'Неверное имя пользователя или пароль.', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'forgot-password', N'en', N'Forgot password', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'forgot-password', N'lt', N'Pamiršote slaptažodį', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'forgot-password', N'ru', N'Забыли пароль', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'forward', N'en', N'Forward', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'forward', N'lt', N'Pirmyn', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'forward', N'ru', N'Вперед', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'found-x-devices', N'en', N'Found {0} devices', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'found-x-devices', N'lt', N'Rasti {0} įrenginiai', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'found-x-devices', N'ru', N'Найденные {0} устройства', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'from', N'en', N'from', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'from', N'lt', N'nuo', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'from', N'ru', N'от', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'graphs', N'en', N'Graphs', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'graphs', N'lt', N'Grafikai', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'graphs', N'ru', N'Графики', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'hello', N'en', N'Hello', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'hello', N'lt', N'Sveiki', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'hello', N'ru', N'Превед', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'home', N'en', N'Home', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'home', N'lt', N'Pradžia', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'home', N'ru', N'Начало', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'hour', N'en', N'Hour', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'hour', N'lt', N'Valanda', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'hour', N'ru', N'Час', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'id', N'en', N'Id', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'id', N'lt', N'Id', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'id', N'ru', N'Ид', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'interval', N'en', N'Interval', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'interval', N'lt', N'Intervalas', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'interval', N'ru', N'Интервал', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'invertSel', N'en', N'Invert selection', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'invertSel', N'lt', N'Pažymėti atvirkščiai', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'invertSel', N'ru', N'Наоборот', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'year', N'en', N'Year', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'year', N'lt', N'Metai', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'year', N'ru', N'Год', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'yes', N'en', N'Yes', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'yes', N'lt', N'Taip', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'yes', N'ru', N'Да', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'language', N'en', N'Language', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'language', N'lt', N'Kalba', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'language', N'ru', N'Язык', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'last12months', N'en', N'Last 12 months', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'last12months', N'lt', N'Paskutiniai 12 mėnesių', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'last12months', N'ru', N'Последние 12 месяцев', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'last24hours', N'en', N'Last 24 hours', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'last24hours', N'lt', N'Paskutinės 24 valandos', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'last24hours', N'ru', N'Последние 24 часа', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'last7days', N'en', N'Last 7 days', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'last7days', N'lt', N'Paskutinės 7 dienos', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'last7days', N'ru', N'Последние 7 дней', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'line', N'en', N'Line', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'line', N'lt', N'Linija', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'line', N'ru', N'Линия', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'login', N'en', N'Login', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'login', N'lt', N'Prisijungti', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'login', N'ru', N'Войти ', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'logoff', N'en', N'Log Off', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'logoff', N'lt', N'Atsijungti', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'logoff', N'ru', N'Выйти', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'mainInfo', N'en', N'Basic information', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'mainInfo', N'lt', N'Pagrindinė informacija', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'mainInfo', N'ru', N'Основная информация', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'maximum-value', N'en', N'Maximum value', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'maximum-value', N'lt', N'Maksimali vertė', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'maximum-value', N'ru', N'Максимальное значение', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'mdate', N'en', N'Last modified', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'mdate', N'lt', N'Paskutinio redagavimo data', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'mdate', N'ru', N'Дата последнего редактирования', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'metaInfo', N'en', N'Meta information', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'metaInfo', N'lt', N'Meta informacija', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'metaInfo', N'ru', N'Мета информация', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'minimum-value', N'en', N'Minimal value', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'minimum-value', N'lt', N'Minimali vertė', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'minimum-value', N'ru', N'Минимальное значение', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'minute', N'en', N'Minute', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'minute', N'lt', N'Minutė', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'minute', N'ru', N'Минута', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'month', N'en', N'Month', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'month', N'lt', N'Mėnesis', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'month', N'ru', N'Месяц', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'na-info', N'en', N'Not enough information.', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'na-info', N'lt', N'Nepakanka informacijos.', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'na-info', N'ru', N'Не достаточно информации.', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'name', N'en', N'Name', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'name', N'lt', N'Pavadinimas', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'name', N'ru', N'Название', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'next', N'en', N'Next', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'next', N'lt', N'Sekantis', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'next', N'ru', N'Следующий', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'no', N'en', N'No', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'no', N'lt', N'Ne', 0)
GO
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'no', N'ru', N'Нет', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'none', N'en', N'None', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'none', N'lt', N'Joks', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'none', N'ru', N'Невыбран', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'nothing-selected', N'en', N'Nothing selected!', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'nothing-selected', N'lt', N'Nieko nepasirinkta!', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'nothing-selected', N'ru', N'Ничего не выбрано!', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'ok', N'en', N'Ok', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'ok', N'lt', N'Gerai', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'ok', N'ru', N'Хорошо', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'password', N'en', N'Password', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'password', N'lt', N'Slaptažodis', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'password', N'ru', N'Пароль', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'passwordRepeat', N'en', N'Repeat Password', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'passwordRepeat', N'lt', N'Slaptažodis pakartotinai', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'passwordRepeat', N'ru', N'Повторный пароль', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'pie', N'en', N'Pie', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'pie', N'lt', N'Pyragas', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'pie', N'ru', N'Пирог', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'points', N'en', N'Points', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'points', N'lt', N'Taškai', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'points', N'ru', N'Точки', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'quarter', N'en', N'Quarter', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'quarter', N'lt', N'Ketvirtis', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'quarter', N'ru', N'Квартал', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'question', N'en', N'Question', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'question', N'lt', N'Klausimas', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'question', N'ru', N'Вопрос', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'real-value', N'en', N'Real value', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'real-value', N'lt', N'Reali vertė', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'real-value', N'ru', N'Реальное значение', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'refresh', N'en', N'Refresh', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'refresh', N'lt', N'Atnaujinti', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'refresh', N'ru', N'Обновить', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'register', N'en', N'Register', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'register', N'lt', N'Registruotis', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'register', N'ru', N'Регистрироваться', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'registered-success', N'en', N'Registered successfully! You may login now!', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'registered-success', N'lt', N'Sėkmingai užsiregistravote! Galite prisijungti dabar!', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'registered-success', N'ru', N'Вы успешно зарегистрировались! Можете присоединиться сейчас!', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'registering...', N'en', N'Registering...', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'registering...', N'lt', N'Registruojama...', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'registering...', N'ru', N'Регистрация...', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'reports', N'en', N'Reports', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'reports', N'lt', N'Ataskaitos', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'reports', N'ru', N'Отчеты', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'retry-later', N'en', N'Retry later...', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'retry-later', N'lt', N'Bandykite dar kartą vėliau...', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'retry-later', N'ru', N'Повторите попытку позже...', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'save', N'en', N'Save', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'save', N'lt', N'Išsaugoti', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'save', N'ru', N'Сохранить', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'scatter', N'en', N'Scatter', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'scatter', N'lt', N'Taškai', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'scatter', N'ru', N'Точки', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'second', N'en', N'Second', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'second', N'lt', N'Sekundė', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'second', N'ru', N'Секунда', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'selectAll', N'en', N'Select all', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'selectAll', N'lt', N'Pažymėti visus', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'selectAll', N'ru', N'Выбрать всех', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'select-chart-type', N'en', N'Select chart type!', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'select-chart-type', N'lt', N'Pasirinkite diagramos tipą!', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'select-chart-type', N'ru', N'Выберите тип диаграммы!', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'select-datapoints', N'en', N'Select data points', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'select-datapoints', N'lt', N'Pasirinkite duomenų taškus', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'select-datapoints', N'ru', N'Выберите точки данных', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'select-devices', N'en', N'Select devices', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'select-devices', N'lt', N'Pasirinkite įrenginius', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'select-devices', N'ru', N'Выберите устройства', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'selectNone', N'en', N'Remove selection from all the elements', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'selectNone', N'lt', N'Atžymėti visus', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'selectNone', N'ru', N'Удалить выделение у всех элементов', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'server', N'en', N'Server', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'server', N'lt', N'Serveris', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'server', N'ru', N'Сервер', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'settings', N'en', N'Settings', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'settings', N'lt', N'Nustatymai', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'settings', N'ru', N'Настройки', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'share', N'en', N'Share', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'share', N'lt', N'Dalintis', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'share', N'ru', N'Делиться', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'submit', N'en', N'Submit', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'submit', N'lt', N'Pateikti', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'submit', N'ru', N'Передать', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'sum', N'en', N'Sum', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'sum', N'lt', N'Suma', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'sum', N'ru', N'Сумма', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'sure', N'en', N'Are you sure you want to continue with this operation?', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'sure', N'lt', N'Ar tikrai norite tęsti šį veiksmą?', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'sure', N'ru', N'Вы уверены, что хотите продолжить эту операцию?', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'sure-delete', N'en', N'Are you sure you want to delete this record?', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'sure-delete', N'lt', N'Ar tikrai norite ištrinti šį įrašą?', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'sure-delete', N'ru', N'Вы уверены, что хотите удалить эту запись?', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'this-year', N'en', N'This year', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'this-year', N'lt', N'Šie metai', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'this-year', N'ru', N'Текущий год', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'this-month', N'en', N'This month', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'this-month', N'lt', N'Šis mėnuo', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'this-month', N'ru', N'Текущий месяц', 0)
GO
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'this-week', N'en', N'This week', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'this-week', N'lt', N'Ši savaitė', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'this-week', N'ru', N'Текущая неделя', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'type', N'en', N'Type', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'type', N'lt', N'Tipas', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'type', N'ru', N'Тип', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'to', N'en', N'to', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'to', N'lt', N'iki', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'to', N'ru', N'до', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'today', N'en', N'Today', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'today', N'lt', N'Šiandien', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'today', N'ru', N'Сегодня', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'tree', N'en', N'Tree', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'tree', N'lt', N'Medis', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'tree', N'ru', N'Дерево', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'uncategorized', N'en', N'Uncategorized', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'uncategorized', N'lt', N'Neįtraukta į kategorijas', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'uncategorized', N'ru', N'Без категории', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'unknown', N'en', N'Unknown', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'unknown', N'lt', N'Nežinoma', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'unknown', N'ru', N'Неизвестный', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'user-settings', N'en', N'User''s Settings', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'user-settings', N'lt', N'Vartotojo nustatymai', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'user-settings', N'ru', N'Пользовательские настройки', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'wallet', N'en', N'Wallet', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'wallet', N'lt', N'Piniginė', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'wallet', N'ru', N'Кошелек', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'week', N'en', N'Week', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'week', N'lt', N'Savaitė', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'week', N'ru', N'Неделя', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'x-selected', N'en', N'Selected {0} item(s).', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'x-selected', N'lt', N'Pasirinkta {0} įrašų.', 0)
INSERT [dbo].[tblUiWord] ([Alias], [Code], [Text], [Autoadded]) VALUES (N'x-selected', N'ru', N'Выбрано {0} записей.', 0)
